### ISSUE TITLE
Having trouble understanding the selection of base distribution

### ISSUE THREAD

**Issue by moonman925** [MokkeMeguru/TFGENZOO#30]
Hello Mokke, me again!
I was reading your code from `glow-realnvp-tutorial` the glow part. I am a bit confused about the selection of base distribution and how the event shape transformed into [32,32,2] finally ( wired tfp).
You were using `tfd.Normal(0,1)` in your code which I believe it have event shape `[]`, and the flow (transformed distribution) have event shape `[32,32,2]`. I kinda confused how it got transformed into `[32,32,2]`... I have trouble understanding the event shape in tfp as well. 
And also I noticed you mention here https://github.com/MokkeMeguru/glow-realnvp-tutorial/issues/2#issuecomment-571774188 , that we can use `MultivariateNormalDiag` instead. How this works or would it be different?
Can you please clear my confusion a bit for me? Thx!

**Comment by MokkeMeguru** [comment]
You should know Flow-based Model's MND means not X \sim N(0, 1) (X means a matrix).
It's x_{i, j} \sim N(0, 1) (0<i<n, 0<j<m) (x_{i,j} is a scalar).

MultivariateNormalDiag creates x_{i, j}

ref. https://github.com/tensorflow/probability/issues/720

**Comment by moonman925** [comment]
Cool, thanks for replying! But how can I sample directly from the `flow`?
Since `flow` has `event_shape` of `(32,32,2)` which I kinda confuse why `(32, 32,2)` not `(32,32,3)` of`(32,32,1)`, so I use `flow.sample(1)`  to sample one image from the trained flow, but it throws errors:
```
ensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,16,16,8] vs. [4] [Op:AddV2] name: chain_of_invert_Unsqueeze_0_of_Blockwise3D_0_of_Flowsteps_0_of_Squeeze_0Normal/sample/chain_of_invert_Unsqueeze_0_of_Blockwise3D_0_of_Flowsteps_0_of_Squeeze_0/forward/Flowsteps_0/forward/actnorm/forward/add/
```

**Comment by MokkeMeguru** [comment]
Sorry, I don’t know your (my) error code in your experience, But I can tell you the advice that my TFGENZOO's implementation uses factor out like Glow.
So, the volume of the tensor is reduced by factor out layer.
e.g.

[32, 32, 3] -> (squeeze) -> [16, 16, 12] -> (factor-out) -> [16, 16, 6] -> (squeeze) -> [8, 8, 24] ...

So If you sample from latent, you should think this factor-out system.

**Comment by moonman925** [comment]
OK, so when we want to generate some images, we sample latent from a standard Gaussian distribution and pass it through the bijectors which should include factor-outs, and we can't directly sample a image from the transformed distribution ( `self.flow` in your code ), is that right?

**Comment by MokkeMeguru** [comment]
In Glow, it's correct. But I want to write use factor-outed volume. So I will write the tutorial using it by fixing this line (https://github.com/MokkeMeguru/TFGENZOO/blob/master/TFGENZOO/examples/glow_mnist/trainer.py#L185)

**Comment by moonman925** [comment]
Thanks, I think my confusion is gone now! I didn't noticed code is different between the tutorial and this repo. Nice works! Always impressed by your code!

**Comment by MokkeMeguru** [comment]
My code is simpler than TensorFlow-probabilities implementation. And Also, This repository is supported by a Japanese company (as my internship). So this will be published as a library.
