### ISSUE TITLE
importerror after setup

### ISSUE THREAD

**Issue by moonman925** [MokkeMeguru/TFGENZOO#39]
```
from TFGENZOO.flow.glow_mnist import trainer
trainer.main()
```
after `python setup.py`
throws error:
`ImportError: cannot import name 'SequentialWithKwargs' from 'TFGENZOO.flows.affine_coupling' (.../lib/python3.7/site-packages/TFGENZOO-0.1.0a0-py3.7.egg/TFGENZOO/flows/affine_coupling.py)`

Anything should be noticed before setup?

**Comment by moonman925** [comment]
What is `zaux` btw.

**Comment by MokkeMeguru** [comment]
sorry, I'll update some layer.
zaux means factor-outed volumes. So if flow-based model factor-out z_i, zaux will be [z_{i-1}, z_i]

**Comment by moonman925** [comment]
z_{i-1} remains the same and z_i passed through next bijectors or the other way around, right ? (Don't be sorry, you are making the world a better place)

**Comment by MokkeMeguru** [comment]
I can show you the abstruction of zaux production process here.
```
original
[32, 32, 3] -> (squeeze) -> [16, 16, 12] -> (factor-out) -> [16, 16, 6] -> (squeeze) -> [8, 8, 24]  -> 
                                                                        V
                    zaux []                                zaux [] <- z1 [16, 16, 6]             zaux [8,8,24]

-> (factor-out) -> [8, 8, 12]     -> (squeeze)         -> [4, 4, 48]  -> ...
           V
 zaux [8, 8, 24] <- z2 [8, 8, 12]     zaux [4, 4, 36 * 4]
```
