### ISSUE TITLE
Why shift in affine coupling has one more dimension then scale

### ISSUE THREAD

**Issue by gitlabspy** [MokkeMeguru/TFGENZOO#69]
https://github.com/MokkeMeguru/TFGENZOO/blob/001cbb2e3dd01a734b1c9d80d971ea82f7befca2/TFGENZOO/flows/affine_coupling.py#L83
`[0:2]` while scale `[1:2]'. Shouldn't be same size for both of them like '[0:1]' and '[1:2]'?

**Comment by gitlabspy** [comment]
I was totally blind.. So sorry...

**Comment by MokkeMeguru** [comment]
No problem, 
I'm happy that your doubts have been resolved :D
