### ISSUE TITLE
Do you interested with TTS problem

### ISSUE THREAD

**Issue by dathudeptrai** [MokkeMeguru/TFGENZOO#71]
hi @MokkeMeguru, thanks for your great work. I'm a creator of TensorflowTTS, https://github.com/dathudeptrai/TensorflowTTS. I'm planning to implement some flow, glow TTS model like flow-tts, glow-tts, waveglow. Do you want to collaborate with me ?

**Comment by MokkeMeguru** [comment]
My answer to that question is Simple:
"Of course, Yes"

**Comment by dathudeptrai** [comment]
@MokkeMeguru we need private channel to communicate :))), how about slack ?

**Comment by MokkeMeguru** [comment]
I have slack account. How to share you?
my mail address is meguru.mokke@gmail.com

**Comment by dathudeptrai** [comment]
@MokkeMeguru i just create slack and invited you :D
