### ISSUE TITLE
Any tips on pre-build the model?

### ISSUE THREAD

**Issue by gitlabspy** [MokkeMeguru/TFGENZOO#83]
There's a step of a type of flow in flow steps need to know about the batch_size, how can I pre-build the model so that the `batch_size` will feed into model when instantiating a model class like `glow` in your TFGENZOO_EXAMPLE repo? 😄

**Comment by MokkeMeguru** [comment]
Sorry give me some example of your problem.
Or you can see my some examples In my each flow-based layer.

https://github.com/MokkeMeguru/TFGENZOO/blob/master/TFGENZOO/flows/inv1x1conv.py#L66-L83

**Comment by MokkeMeguru** [comment]
I don't know the case of needing fixed-length batch-size.

**Comment by gitlabspy** [comment]
Thx! I stop tinkering with the batch_size though.
