### ISSUE TITLE
Any ways to pass constant into a flow component?

### ISSUE THREAD

**Issue by gitlabspy** [MokkeMeguru/TFGENZOO#85]
```
for k in range(K):
                fml.append(Actnorm())
                fml.append(Inv1x1Conv())
                fml.append(
                    AffineCoupling(
                        mask_type=AffineCouplingMask.ChannelWise,
                        scale_shift_net_template=lambda x: ShallowResNet(
                            x, width=self.model_params["hidden_width"]
                        ),
                    )
                )
flows.append(FlowModule(fml))
```
Let's say `x1` is a batch of imgs,  I need to pass some kinda label thing `x2` ,which is same size as `x1` and unique to `x1`, to AffineCoupling to transform `x1`. 
Is there any way to achieve this?

**Comment by MokkeMeguru** [comment]
ConditionalAffincCoupling Layer can do so

**Comment by MokkeMeguru** [comment]
Take a 24 hour to implement the example...

**Comment by gitlabspy** [comment]
Thx! 😄

**Comment by MokkeMeguru** [comment]
https://github.com/MokkeMeguru/TFGENZOO/blob/master/tutorials/02_conditional_flow-based_model.ipynb
is the tutorial to add conditional input into flow-based model.

(Please close the issue, if do it, I'll lose the issue...)

@gitlabspy

**Comment by gitlabspy** [comment]
Nice work! Thanks a lot!
You mean I close it again? Or you want to keep this issue open?

**Comment by MokkeMeguru** [comment]
Your welcome
If my answer is complete for you, please close it.

**Comment by gitlabspy** [comment]
Yeah, it totally solved my problem!
